# Site settings
baseurl = "http://vitiylucas.com/"
languageCode = "en-us"
title = "Viti y Lucas"
theme = "hugo-agency-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) or
	# most longer texts.
	#
	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Your name"
	description = "Your description"

	# Since this template is static, the contact form uses www.formspree.io as a
	# proxy. The form makes a POST request to their servers to send the actual
	# email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
	email = "lauluppani@gmail.com"


	# Navigation
	[params.navigation]
		ceremonia = "Ceremonia"
		rsvp = "RSVP"
		regalos = "Regalos"
		brand = "V&L"
		como_llegar = "Cómo llegar"
		galeria = "Galería"
		vitiylucas = "#Vitiylucas"

	# Hero section
	[params.hero]
		title = "Viti y Lucas"
		subtitle = "¡Nos casamos!"
		date = "30 • 01 • 2016"
		buttonText1 = "Agendar"
		buttonText2 = "RSVP"


	# Ceremonia section
	[params.ceremonia]
		title = "Ceremonia"


    # RSVP section
	[params.rsvp]
		title = "R.S.V.P."
		subtitle  = "Vas a venir?"
		buttonText = "RSVP"

		# 'warning' defines error messages for invalid inputs
		[params.rsvp.form.name]
			text = "Nombre *"
			warning = "Por favor, ingresá tu nombre."

		[params.rsvp.form.lastname]
			text = "Apellido *"
			warning = "Por favor, ingresá tu apellido."

		[params.rsvp.form.email]
			text = "Email *"
			warning = "Por favor, ingresá tu email."

		[params.rsvp.form.song]
			text = "Cuál es tu canción favorita?"
			warning = "Please enter your phone number."

	# Regalos section
	[params.regalos]
		title = "Regalos"

	# Cómo llegar section
	[params.como_llegar]
		title = "Cómo llegar"
		subtitle = "Dónde quedarse"

	# Galería section
	[params.galeria]
		title = "Galería"


	# Footer section
	[params.footer]
		title = "Spread the love..."
